name: Java CI with Maven

on:
  push:
    branches:
      - main  # only push to main branch
  pull_request:
    branches:
      - main  # all PRs to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the runner
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Vendor: AdoptOpenJDK Temurin
          java-version: '17'

      # Cache Maven dependencies to speed up the build process
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project with Maven
      - name: Build with Maven
        run: mvn -B clean install

      # Run tests
      - name: Run tests
        run: mvn test
